name: victorkozlov
favicon: null
layout_spectrum: 0.819035061635077
typography_spectrum: 0.2936229819897562
title: Victor Kozlov
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.006769942585378885
  lightness: 0.9571684191469103
  saturation: 0.47622440406121314
  rhythmicContrast: 0.3575376565568149
purpose: []
